### ISSUE TITLE
Strange results when writing two currencies

### ISSUE THREAD

**Issue by DrorHarari** [AvatarHurden/keypirinha-currency#7]
At this time, 10 EUR are 11.50 USD as below:
![image](https://user-images.githubusercontent.com/1831901/51018210-733e3f80-157f-11e9-8a82-1197b6115a99.png)

When typing `10 usd eur` we're getting as a result:
![image](https://user-images.githubusercontent.com/1831901/51018255-a08aed80-157f-11e9-87bc-2e4ca85294c6.png)

Which I would have guessed means 10 US dollars as Euros, but what we see is the result of 11.15 USD which is like the calculation of `10 * EUR/USD` which is very confusing (not good with money).

BTW, my current configuration is:
```
[defaults]
input_cur = USD
output_cur = USD
             EUR
             ILS
             GBP
             JPY
```

**Comment by tchokido** [comment]
where do you edit your preference for this plugin ?

**Comment by AvatarHurden** [comment]
@DrorHarari Actually, the plugin is calculating 10 USD + 1 EUR. This is because of the way I designed the grammar, making the addition or subtraction operator between currencies optional and, when there are no numbers provided, assuming you meant 1 of the currency. 

Assuming 1 when no value is provided is good for showing exchange rates (`EUR in USD`), but can be confusing for this case. In the next version I'll probably make the operators between currencies mandatory (while still allowing something like `10 USD + EUR` to be interpreted as `10 USD + 1 EUR`) and make the final separator (`in`, `to`, etc) optional (which would allow `10 USD EUR` to be interpreted as `10 USD in EUR`).

I think this would be the best approach. Any thoughts?

@tchokido You can search for 'Configure currency' and there should be an item that opens up the configuration file.

More information can be found in [this link](http://keypirinha.com/configuration.html).

**Comment by DrorHarari** [comment]
@AvatarHurden I was wondering what was the number I was getting... 8-)

Your suggestion makes perfect sense. I appreciate the insight and am thankful for the very useful extension!

/d

**Comment by AvatarHurden** [comment]
Version 2.1 changes the grammar and should be more intuitive. Let me know if you run into any other edge cases!
